//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListSearchSQLLiteEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class wSystemValve
    {
        public long OBJECTID { get; set; }
        public string FACILITYID { get; set; }
        public string LOCDESC { get; set; }
        public string VALVETYPE { get; set; }
        public Nullable<short> BYPASSVALVE { get; set; }
        public Nullable<short> CLOCKTOCLOSE { get; set; }
        public Nullable<short> NORMALLYOPEN { get; set; }
        public Nullable<int> TURNSTOCLOSE { get; set; }
        public Nullable<short> OPERABLE { get; set; }
        public Nullable<short> HYDRFLAG { get; set; }
        public Nullable<short> CURROPEN { get; set; }
        public Nullable<short> ENABLED { get; set; }
        public Nullable<short> ACTIVEFLAG { get; set; }
        public Nullable<short> OWNEDBY { get; set; }
        public Nullable<short> MAINTBY { get; set; }
        public string LASTEDITOR { get; set; }
    }
}
